--   -------------------------------------------------- 
--   generated by enterprise architect version 10.0.1008
--   created on : tuesday, 03 august, 2021 
--   dbms       : mysql 
--   -------------------------------------------------- 

--  create tables 
create table materiales_utilizados
(
	detalle_pedido_id bigint,
	material_id bigint,
	cantidad decimal(10,2),
	unidad_medida bigint,
	key (detalle_pedido_id),
	key (material_id)

) 
;


create table pagos
(
	id bigint ,
	pedido_id bigint,
	abono decimal(15,4),
	fecha_abono date,
	descripcion varchar(50),
	key (pedido_id)

) 
;


create table productos
(
	id bigint not null AUTO_INCREMENT comment 'identificador unico',
	codigo varchar(20) not null comment 'codigo del producto',
	nombre varchar(80) not null comment 'nombre del producto que vende la empresa',
	descripcion varchar(150) comment 'en este campo puede ir una descripcion de las caracteristicas que tiene el producto',
	estado char(2) comment 'estado del producto activo/inactivo',
	calcular_precio char(1),
	precio_predeterminado decimal(10,4),
	primary key (id),
	unique uq_productos_codigo(codigo),
	unique uq_productos_id(id),
	unique uq_productos_nombre(nombre)

)  comment='productos que maneja la empresa'
;


create table detalle_pedido_cliente
(
	id bigint not null AUTO_INCREMENT comment 'idenfiticador unico',
	pedido_id bigint not null comment 'encabezado del pedido',
	producto_id bigint not null comment 'producto solicitado',
	comentario varchar(100) comment 'comentario de cosas extras que solicite el cliente',
	costo_adicional decimal(15,4) default 0 comment 'si incluye algun costo adicional el producto que no fue esperado',
	costo_instalacion decimal(15,4) default 0 comment 'costo de instalacion',
	descuento decimal(10,4) default 0 comment 'descuento que se incluya al producto',
	cantidad decimal(10),
	monto decimal(15,4) default 0 comment 'precio final del producto',
	necesita_materiales char(1),
	primary key (id),
	unique uq_producto_fabricado_id(id),
	key (pedido_id),
	key (producto_id)

)  comment='tabla para guardar el producto solicitado'
;


create table usuarios
(
	usuario varchar(15) not null comment 'nombre de usuario ',
	dpi varchar(13),
	password text comment 'contraseña',
	nombre varchar(80) comment 'nombre de usuario',
	direccion varchar(100),
	telefono varchar(13),
	perfil text comment 'perfil del usuario',
	foto text comment 'foto del  usuario',
	estado char(1) not null default 'A' comment 'estado del usuario   activo / inactivo',
	ultimo_login datetime comment 'ultimo ingreso del usuario',
	fecha_registro datetime comment 'fecha de registro del usuario',
	primary key (usuario)

)  comment='tabla de usuarios del sistema'
;


create table materiales
(
	id bigint not null comment 'identificador unico',
	codigo varchar(20),
	nombre varchar(80),
	descripcion varchar(50),
	proveedor_id bigint,
	precio_venta decimal(15,4) comment 'total por material utilizado',
	precio_compra decimal(15,4),
	stock decimal(15,4),
	telefono_notificacion varchar(13),
	email_notificacion varchar(100),
	fecha_registro datetime,
	fecha_modificacion datetime,
	estado char(1),
	primary key (id),
	unique uq_materiales_fabricacion_id(id),
	key (proveedor_id)

)  comment='materiales de la fabricacion'
;


create table pedidos
(
	id bigint not null comment 'identificador unico',
	cliente_id bigint,
	comentario varchar(200) comment 'comentario extra sobre el pedido, por ejemplo si el cliente quiere un detalle en especial ',
	estado char(3) comment 'estado para saber en que fase se encuentra el pedido',
	total decimal(15,4) not null default 0 comment 'total a pagar',
	total_pagado decimal(10,4),
	total_pendiente decimal(10,4),
	fecha_ingreso datetime comment 'fecha que se ingreso el pedido',
	fecha_entrega datetime comment 'fecha de entrega del pedido',
	fecha_modificacion datetime comment 'fecha de modificacion del registro',
	usurio_registro varchar(20) comment 'usuario que modifico el registro',
	usuario_modifica varchar(20) comment 'usuario que realizo la ultima modificacion',
	direccion varchar(100) comment 'direccion en donde se instalara el pedido',
	usuario_asignado varchar(20),
	primary key (id),
	unique uq_pedido_id(id),
	key (cliente_id)

) 
;


create table clientes
(
	id bigint not null comment 'identificador unico',
	dpi varchar(13),
	nit varchar(13) comment 'nit del cliente si requiere factura',
	nombre varchar(80) not null comment 'nombre del cliente',
	domicilio varchar(120) comment 'direccion para envio del pedido',
	telefono_uno varchar(15) not null comment 'telefono de contacto',
	telefono_dos varchar(15) comment 'telefono adicional al que puedan llamar',
	correo_electronico varchar(100) comment 'correo electronico para notificaciones',
	primary key (id),
	unique uq_clientes_id(id),
	unique uq_clientes_nombre(nombre)

)  comment='tabla para guardar el nuevo cliente'
;


create table proveedores
(
	id bigint not null comment 'identificador unico',
	nombre varchar(80) not null comment 'nombre de la empresa',
	telefono varchar(15),
	correo_electronico varchar(150),
	direccion varchar(150) comment 'direccion del proveedor',
	descripcion varchar(100) comment 'descripcion para explicar que provee esa empresa',
	primary key (id),
	unique uq_proveedores_id(id)

)  comment='tabla para guardar los proveedores de materiales de la empresa'
;





--  create foreign key constraints 
alter table materiales_utilizados add constraint fk_materiales_utilizados_detalle_pedido_cliente 
	foreign key (detalle_pedido_id) references detalle_pedido_cliente (id)
;

alter table materiales_utilizados add constraint fk_materiales_utilizados_materiales 
	foreign key (material_id) references materiales (id)
;

alter table pagos add constraint fk_pagos_pedido_pedido_cliente 
	foreign key (pedido_id) references pedidos (id)
;

alter table detalle_pedido_cliente add constraint fk_detalle_pedido_pedido 
	foreign key (pedido_id) references pedidos (id)
;

alter table detalle_pedido_cliente add constraint fk_detalle_pedido_productos 
	foreign key (producto_id) references productos (id)
;

alter table materiales add constraint fk_tlc_materiales_fabricacion_tlc_proveedores 
	foreign key (proveedor_id) references proveedores (id)
;

alter table pedidos add constraint fk_pedido_clientes 
	foreign key (cliente_id) references clientes (id)
;
